[versions]
agp = "8.13.0"
core = "5.0.0"
coreSplashscreen = "1.2.0-rc01"
coreVersion = "3.5.3"
kotlin = "2.0.10"
ksp = "2.0.10-1.0.24"
composeCompiler = "1.5.3"
coreKtx = "1.16.0"
lifecycleRuntimeKtx = "2.9.2"
lifecycleViewModelCompose = "2.9.2"
activityCompose = "1.10.1"
composeBom = "2025.07.00"
hiltNavigationCompose = "1.2.0"
navigationCompose = "2.8.5"
serialization = "1.7.3"
ktor = "3.2.2"
multimult = "0.2.4"
web3authAndroidSdk = "9.0.4"
web3Solana = "0.2.5"
rpcCore = "0.2.8"
mobileWalletAdapterClientlibKtx = "2.0.8"
sol4k = "0.4.1"
hilt = "2.57"
junit = "4.13.2"
androidxJunit = "1.2.1"
espressoCore = "3.6.1"
junitVersion = "1.2.1"
composeMarkdown = "0.5.4"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
core = { module = "org.web3j:core", version.ref = "core" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
mobile-wallet-adapter-clientlib-ktx = { module = "com.solanamobile:mobile-wallet-adapter-clientlib-ktx", version.ref = "mobileWalletAdapterClientlibKtx" }
multimult = { module = "io.github.funkatronics:multimult", version.ref = "multimult" }
rpc-core = { module = "com.solanamobile:rpc-core", version.ref = "rpcCore" }
web3-solana = { module = "com.solanamobile:web3-solana", version.ref = "web3Solana" }
sol4k = { module = "org.sol4k:sol4k", version.ref = "sol4k" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleViewModelCompose" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-android = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor" }
dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
web3auth-android-sdk = { module = "com.github.Web3Auth:web3auth-android-sdk", version.ref = "web3authAndroidSdk" }
zxing-core = { module = "com.google.zxing:core", version.ref = "coreVersion" }
compose-markdown = { module = "com.github.jeziellago:compose-markdown", version.ref = "composeMarkdown" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }